version: 2.1
executors:
  frontend:
    working_directory: ~/repo
    # environment:
    #   DIST_DIR: public
    docker:
    - image: node:12.18.4
  cypress:
    docker:
      - image: cypress/base:10
    # environment:
    #   - CYPRESS_CACHE_FOLDER: /tmp/.cache/Cypress
    #   - IMAGE_NAME: cypress
jobs:
  e2e:
    executor: cypress
    steps:
      - attach_workspace:
          at: .
      - run: ls
      - run: pwd
      - run: yarn test:e2e
  build_front:
    executor: frontend
    steps:
      - checkout
      - run: ls
      - run: pwd
      - restore_cache:
          name: Restore Yarn Package Cache
          keys:
            - cache-key-{{ checksum "yarn.lock" }}
      - run:
          name: Install Dependencies
          command: yarn install --frozen-lockfile
      - save_cache:
          name: Save Package and cypress Cache
          key: cache-key-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/Cypress
            - ~/.cache/yarn
      - persist_to_workspace:
          root: .
          paths:
            - .
workflows:
  version: 2
  dev_workflow:
    jobs:
      - build_front
      - e2e:
          requires:
          - build_front
