version: 2.1
jobs:
  e2e:
    working_directory: ~/repo
    docker:
      - image: node:12.16.1
    steps:
      - attach_workspace:
          at: .
      - run: ls
      - run: yarn test:e2e
  initial:
    working_directory: ~/repo
    docker:
      - image: node:12.16.1
    steps:
      - checkout
      - restore_cache:
          name: Restore Yarn Package Cache
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}
      - run:
          name: Install Dependencies
          command: yarn install --frozen-lockfile
      - save_cache:
          name: Save Yarn Package Cache
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn
      - persist_to_workspace:
          root: .
          paths:
            - .
workflows:
  version: 2
  dev_workflow:
    jobs:
      - initial
      - e2e:
        requires:
          - initial
