# 参考 https://future-architect.github.io/articles/20200115/
name: e2e test
on: [push]
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: install
        run: yarn install
      - name: test:e2e
        run: yarn test:e2e

